routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// \Event::listen('Illuminate\Database\Events\QueryExecuted', function ($query) {
//     echo'<pre>';
//     var_dump($query->sql);
//     var_dump($query->bindings);
//     var_dump($query->time);
//     echo'</pre>';
// });

// ******** Migração de rotas novas ******** //

//Proteçao para caracteres numericos, na versão 5.4 muda forma de implementar
Route::pattern('id', '[0-9]+');
Route::pattern('client_id', '[0-9]+');

//Rotas de autenticaçao
//Route::auth();

/*
********************** Autenticação **********************
*/
//Route::auth();
Route::group(['middleware' => ['web']], function() {

// Login Routes...
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
    Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
    Route::post('reset', ['as' => 'reset.post', 'uses' => 'Auth\LoginController@reset']);

// Registration Routes...
    //Route::get('register', ['as' => 'register', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
    //Route::post('register', ['as' => 'register.post', 'uses' => 'Auth\RegisterController@register']);

// Password Reset Routes...
    Route::get('password/reset', ['as' => 'password.reset', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
    Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
    Route::get('password/reset/{token}', ['as' => 'password.reset.token', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
    //Route::post('password/reset', ['as' => 'password.reset.post', 'uses' => 'Auth\ResetPasswordController@reset']);
    Route::post('password/reset', ['as' => 'password.reset.post', 'uses' => 'Crm\USerController@postAlterarSenha']);
});

//Gerenciamento de perfil pelo usuário
Route::group(array('middleware' => 'auth', 'namespace' => 'Crm', 'prefix' => 'perfil'), function()
{
  Route::get('/', 'UserController@getPerfil');
  //Route::get('alterar-senha', 'UserController@alterarSenha');
  Route::post('alterar-senha', 'UserController@postAlterarSenha');
});


//Busca
Route::group(array('middleware' => ['auth','needsRoleOrPermission'], 'namespace' => 'Crm', 'prefix' => 'busca'), function()
{
  Route::get('avancada', 'BuscaController@getAvancada');
  Route::get('clientes', 'BuscaController@getClientes');

});

//Dashboard
Route::group(array('middleware' => 'auth', 'namespace' => 'Crm'), function()
{
  Route::get('/', 'DashboardController@index');
  Route::resource('dashboard', 'DashboardController');
});

//Lista de clientes
Route::group(array('middleware' => 'auth', 'namespace' => 'Crm', 'prefix' => 'clientes'), function()
{
  Route::get('/', ['as' => 'clientes' ,'middleware' => ['auth','needsRoleOrPermission'], 'is' => ['superuser'], 'shield' => 'client.create', 'any' => true, 'uses' => 'ClientController@getIndex']);
  Route::get('selecionar-responsavel/{client_id?}/{resposavel_id?}', 'ClientController@getViewSelectResponsible');
  Route::post('selecionar-responsavel/', ['as' => 'clientes' ,'middleware' => ['auth','needsRoleOrPermission'],'is' => ['superuser'], 'shield' => 'client.edit', 'any' => true, 'uses' => 'ClientController@changeClientResponsible']);
  Route::get('meus-clientes', ['as' => 'clientes' ,'middleware' => ['auth','needsRoleOrPermission'], 'is' => ['consultores'], 'shield' => 'client.create', 'any' => true, 'uses' => 'ClientController@getMeusClientes']);
});

//Cliente -> Recursos
Route::resource('cliente', 'Crm\Cliente\ClienteController', ['only' => ['store','destroy']]);
Route::group(array('middleware' => 'auth', 'namespace' => 'Crm\Cliente', 'prefix' => 'cliente'), function()
{
  //Cliente
  Route::get('/novo-cliente', 'ClienteController@getNovoCliente');
  Route::get('/novo-lead', 'ClienteController@getNovoLead');

  //Resumo
  Route::resource('resumo', 'ResumoController');

  //Dados
  Route::resource('dados', 'DadosController');

  //Contatos
  Route::get('/contatos/{contato}/novo-contato', 'ContatosController@getNovoContato');
  Route::get('/contatos/lista-simples/{contato}', 'ContatosController@getListaSimples');
  Route::get('/contatos/mover/{cliente}/{contato}', 'ContatosController@getMoverContato');
  Route::put('/contatos/mover/{contato}', 'ContatosController@putMoverContato');
  Route::resource('contatos', 'ContatosController');

  //Formas de Contatos
  Route::resource('formas-de-contato', 'FormasContatoController', ['only' => ['store', 'destroy']]);

  //Produtos de um contato
  Route::resource('produtos', 'ProdutosContatoController', ['only' => ['store', 'destroy']]);

  //Historico de interações
  Route::resource('interacoes', 'InteracoesController');

  //Financeiro
  Route::put('/financeiro/dados-cobranca/{client_id?}', 'FinanceiroController@putDadosCobranca');
  Route::put('/financeiro/endereco-cobranca/{client_id?}', 'FinanceiroController@putEnderecoCobranca');
  Route::post('/financeiro/historico-cobranca/{client_id?}', 'FinanceiroController@postHistoricoCobranca');
  Route::resource('financeiro', 'FinanceiroController', ['only' => ['index', 'show']]);

  //Relevancia
  Route::resource('relevancia', 'RelevanciaController', ['only' => ['index', 'show']]);

});

//Rotas para interações via modals
Route::get('interacao/nova-interacao/{client_id?}/{father_id?}', 'Crm\ClientController@getEscolheInteracao');
Route::get('interacao/visualizar/{client_id?}/{interaction_id?}', 'Crm\ClientController@getViewInteracao');
Route::get('interacao/mover/{client_id?}/{interaction_id?}', 'Crm\ClientController@getMoveInteraction');
Route::put('interacao/mover/{client_id?}/{interaction_id?}', 'Crm\ClientController@putMoveInteraction');
Route::post('interacao/salvar-interacao/simples/{id?}', 'Crm\ClientController@postInteracaoSimples');

/*//Rotas de Importação
Route::group(['middleware' => ['auth', 'needsRoleOrPermission'],'is' => ['superuser'], 'shield' => 'import.index', 'any' => true], function () {
  Route::get('importar', 'Crm\ImportController@index');
  Route::post('importar/clientes', 'Crm\ImportController@postClientes');
  Route::post('importar/contatos', 'Crm\ImportController@postContatos');
  Route::post('importar/produtos', 'Crm\ImportController@postProdutos');
  Route::post('importar/relevancia', 'Crm\ImportController@postRelevancia');
  Route::post('importar/ultimas-interacoes', 'Crm\ImportController@postOrigemLead');
  Route::post('importar/login', 'Crm\ImportController@postLogin');
});

//Rotas de Exportação
Route::group(['middleware' => ['auth', 'needsPermission'], 'shield' => 'export.index', 'any' => true], function () {
  Route::get('exportar', 'Crm\ExportController@index');
  Route::get('exportar/clientes', 'Crm\ExportController@getClientes');
  Route::get('exportar/contatos', 'Crm\ExportController@getContatos');
  Route::get('exportar/produtos', 'Crm\ExportController@getProdutos');
  Route::get('exportar/pagamentos', 'Crm\ExportController@getPagamentos');
  Route::get('exportar/ultimas-interacoes', 'Crm\ExportController@getUltimasInteracoes');
});*/

Route::group(array('middleware' => ['auth','needsPermission'], 'shield' => 'import.index', 'namespace' => 'Crm\Database', 'prefix' => 'database'), function()
{
  Route::get('importar', 'ImportController@index');
  Route::post('importar/clientes', 'ImportController@postClientes');
  Route::post('importar/contatos', 'ImportController@postContatos');
  Route::post('importar/produtos', 'ImportController@postProdutos');
  Route::post('importar/relevancia', 'ImportController@postRelevancia');
  Route::post('importar/ultimas-interacoes', 'ImportController@postOrigemLead');
  Route::post('importar/login', 'ImportController@postLogin');

});

Route::group(array('middleware' => ['auth','needsPermission'], 'shield' => 'export.index', 'namespace' => 'Crm\Database', 'prefix' => 'database'), function()
{
  Route::get('exportar', 'ExportController@index');
  Route::get('exportar/clientes', 'ExportController@getClientes');
  Route::get('exportar/contatos', 'ExportController@getContatos');
  Route::post('exportar/leads', 'ExportController@postLeads');
  Route::get('exportar/produtos', 'ExportController@getProdutos');
  Route::post('exportar/financeiro', 'ExportController@postFinanceiro');
  Route::get('exportar/ultimas-interacoes', 'ExportController@getUltimasInteracoes');
});

Route::group(array('middleware' => ['auth','needsPermission'], 'shield' => 'configuracoes.index', 'namespace' => 'Crm\Configuracoes', 'prefix' => 'configuracoes'), function()
{
  //Usuários
  Route::resource('usuarios', 'UsuarioController');
  //Grupos
  Route::resource('grupos', 'GrupoController');
  //Permissões
  Route::resource('permissoes', 'PermissaoController');
  //Escritórios
  Route::resource('escritorios', 'EscritorioController');

});

// **************** Rotas Antigas **************** //

Route::group(['middleware' => ['auth'], 'prefix' => 'gestao'], function() {
  Route::controller('tipo_interacao', 'Crm\InteractionTypeController');

  // CALENDARIO

  // carrega view do calendario
  Route::get('calendario', ['as' => 'usuarios' ,'middleware' => ['auth','needsRoleOrPermission'],
  'is' => ['superuser'], 'shield' => 'calendario.index', 'any' => true,
  'uses' => 'Crm\CalendarioController@getIndex']);

  // carrega os contatos para exibir no calendario
  Route::get('getContatos', ['as' => 'getContatos', 'middleware' => ['auth','needsRoleOrPermission'],

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Client extends Model
{
    use SoftDeletes;
    protected $fillable = [
        'id',
        'documento',
        'ie',
        'tipo_documento',
        'tipoempresa_id',
        'nome',
        'empresa',
        'endereco',
        'complemento',
        'cidade',
        'estado',
        'cep',
        'segmento',
        'site',
        'user_id',
        'escritorio_id',
        'responsavel_id',
        'status_id',
        'origem_id',
        'id_plataforma',
        'datacadastro_plataforma'
    ];

    public $exportFields = [
        'clients.id',
        'status.status',
        'clients.status_id',
        'clients.documento',
        'clients.tipo_documento',
        'tipoempresa.tipo',
        'clients.tipoempresa_id',
        'clients.nome',
        'clients.empresa',
        'clients.segmento',
        'clients.site',
        'clients.user_id',
        'users.name as criadopor',
        'clients.responsavel_id',
        'user_responsavel.name as responsavel_nome',
        'clients.escritorio_id',
        'escritorios.nome as escritorio',
        'clients.origem_id',
        'origem.origem as origem',
        'clients.id_plataforma',
        'clients.created_at as criadoem',
    ];

    protected $hidden = [];

    //observe this model being deleted and delete the child events
    public static function boot ()
    {
        parent::boot();

        //Grava indice de registros que precisam ser atualizados no IBM WAtson
        self::updated(function (Client $client) {
            $updateIbm = new UpdateIbm();
            $updateIbm->create(['client_id'=>$client->id, 'contact_id'=>null]);
        });
        self::created(function (Client $client) {
            $updateIbm = new UpdateIbm();
            $updateIbm->create(['client_id'=>$client->id, 'contact_id'=>null]);
        });

        //Mapeia dados relacionados e executa delete
        self::deleting(function (Client $client) {
            foreach ($client->interactions as $interaction){
                $interaction->delete();
            }
        });
        self::deleting(function (Client $client) {
            foreach ($client->contacts as $contact){
                $contact->delete();
            }
        });
    }

    public function interactions()
    {
        return $this->hasMany('App\Models\Interaction')->withTrashed();
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id', 'id')->withTrashed();
    }

    public function responsavel()
    {
        return $this->belongsTo('App\Models\User','responsavel_id','id')->withTrashed();
    }

    public function escritorio()
    {
        return $this->belongsTo('App\Models\Escritorio');
    }

    public function contacts()
    {
        return $this->hasMany('App\Models\Contact');
    }

    public function status()
    {
        return $this->belongsTo('App\Models\Status');
    }

    public function origem()
    {
        return $this->belongsTo('App\Models\Origem');
    }


    public function getTipoPessoaAttribute()
    {
        $tipo = $this->attributes['tipo_documento'];
        return $tipo == 1 ? 'Pessoa Física' : 'Pessoa Jurídica';
    }

    public function getTipoPessoaShortAttribute()
    {
        $tipo = $this->attributes['tipo_documento'];
        return $tipo == 1 ? 'PF' : 'PJ';
    }

    public function getDocumentoAttribute()
    {
        return $this->attributes['documento'] == null ? '' : $this->attributes['documento'];
    }

    public function getDocumentocleanAttribute()
    {
        return preg_replace( '/[^0-9]/', '', $this->attributes['documento'] );
    }

    public function getDataCadastroPlataformaAttribute()
    {
        $data = $this->attributes['datacadastro_plataforma'];
        //if ($data == null ? $data = 'Não cadastrado' : $data = date('d/m/Y \à\s H:i', strtotime($data)) );
        if ($data == null ? $data = '' : $data = date('d/m/Y \à\s H:i', strtotime($data)) );
        return $data;
    }

}

app/Models/Interaction.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Interaction extends Model
{
    protected $fillable = [
        'observacao',
        'data_contato',
        'user_id',
        'client_id',
        'interaction_type_id',
        'father_id'
    ];

    use SoftDeletes;
    protected $dates = ['deleted_at'];

    protected $hidden = [];

    public function author()
    {
        return $this->belongsTo('App\Models\User', 'user_id')->withTrashed();
    }

    public function client()
    {
        return $this->belongsTo('App\Models\Client', 'client_id');
    }

    public function interaction_type()
    {
        return $this->belongsTo('App\Models\InteractionType', 'interaction_type_id');
    }

    public function father()
    {
        return $this->belongsTo('App\Models\Interaction', 'father_id');
    }

    public function children()
    {
        return $this->hasOne('App\Models\Interaction', 'father_id');
    }

    public function cart()
    {
        return $this->hasOne('App\Models\Cart');
    }

    public function getDataCriacaoAttribute()
    {
        $data = $this->attributes['created_at'];
        return date('d/m/Y \à\s H:i', strtotime($data));
    }

    public function dataFormatada()
    {
        return date('d/m/Y H:i', strtotime($this->data_contato));
    }

    public function getTituloAttribute()
    {
        $tipo = $this->interaction_type->id;
        $data = $this->attributes['data_contato'];
        if($data == null)
            return $this->inicioObservacao();
      //  if ($tipo == 1)
       //     return 'Entrar em contato em ' . $this->dataFormatada();

        return 'Data: ' . $this->dataFormatada() . " - ". $this->inicioObservacao();
    }

    public function inicioObservacao()
    {
        return $this->observacao;
    }

    public function getTipoId()
    {
        return $this->interaction_type->id;
    }


    public function getTipoInteracaoClassAttribute()
    {
        switch($this->interaction_type->id){
            case 1:
                return 'label-default';
                break;
            case 2:
                return 'label-info';
                break;
            default:
                return 'label-warning';
                break;
        }
    }

    public function getTipoInteracaoAttribute()
    {
        return $this->interaction_type->nome();
    }

    public function getColorAttribute()
    {
      if(!is_null($this->children)){
        return $this->attributes['color'] = "#2ecc71";
      }
    }
}

app/Http/Controllers/Crm/Configuracoes/EscritorioController.php
<?php

namespace App\Http\Controllers\Crm\Configuracoes;

use Illuminate\Http\Request;
use App\Http\Requests;

use App\Http\Controllers\CrmController;

use App\Services\EscritorioService;

class EscritorioController extends CrmController
{
  protected $escritorioService;

  public function __construct(EscritorioService $escritorioService)
  {
      $this->escritorioService = $escritorioService;
  }

  public function index()
  {
    $titulo = 'Escritórios';
    $subtitulo = 'Relação de filiais e parceiros com acesso ao CRM';
    $escritorios = $this->escritorioService->getEscritorios();
    return view('crm.configuracoes.escritorios.index', compact('titulo','subtitulo','escritorios'));
  }
}

resources/views/crm/cliente/index.blade.php
@extends('layouts.base')

@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                  <div class="row">
                    <div class="col-lg-12">
                      <h4 class="title">{{$titulo}} ({{ $clients->total() }})</h4>
                      <p class="category">{{$subtitulo}}</p>
                    </div>
                  </div>
                </div>
                <div class="panel-body">

                    <!-- Row -->
                    <table class="table table-responsive" style="margin-top: 1em;">
                        <thead>
                            <th># <a href="{!! action('Crm\ClientController@getIndex',  array_merge(\Request::except(['orderBy', 'order']), ['orderBy' => 'id'])) !!}" class="pull-right"><i class="fa fa-sort-numeric-asc"></i></a></th>
                            <th>Tipo</th>
                            <th>Documento</th>
                            <th>
                                <a href="{!! action('Crm\ClientController@getIndex', array_merge(\Request::except(['orderBy', 'order']), ['orderBy' => 'empresa', 'order' => 'DESC'])) !!}" class="pull-right"><i class="fa fa-sort-alpha-desc"></i></a>
                                Empresa
                                <a href="{!! action('Crm\ClientController@getIndex', array_merge(\Request::except(['orderBy', 'order']), ['orderBy' => 'empresa'])) !!}" class="pull-right"><i class="fa fa-sort-alpha-asc"></i></a>
                            </th>
                            <th>Estado</th>
                            <th>Status</th>
                            <th>Responsável</th>
                            <th>Ações</th>
                        </thead>
                        <tbody>
                        @foreach ($clients as $client)
                            <tr>
                                <td>#{{ $client->id }}</td>
                                <td>{{ $client->tipo_pessoa_short }}</td>
                                <td>{{ $client->documento }}</td>
                                <td><a href="{{ url('cliente/resumo', $client->id) }}">{{ $client->empresa }}</a></td>
                                <td>{{ $client->estado }}</td>
                                <td><span class="label label-info">@if(isset($client->status)) {{ $client->status->status }} @endif</span></td>
                                <td>@if(isset($client->responsavel)) {{ $client->responsavel->name }} @endif</td>
                                <td>
                                  <div style="padding:12px 0;">
                                    <a href="{{ url('cliente/resumo', $client->id) }}" class="btn btn-fill btn-primary btn-xs" style="float:left;">
                                        <i class="fa fa-edit"></i> Ver
                                    </a>

                                    @is(['Atendimento','Gestores'])
                                        @if(isset($client->responsavel->name))
                                        <button style="float:left;" type="button" onclick="selecionaConsultor({{ $client->id }},{{ $client->responsavel->id }});" class="btn btn-fill btn-xs btn-success">
                                            <i class="fa fa-refresh"></i> Alterar Consultor
                                        </button>

                                        @else
                                          <button style="float:left;" type="button" onclick="selecionaConsultor({{ $client->id }});" class="btn btn-fill btn-xs btn-success">
                                              <i class="fa fa-user-plus"></i> Selecionar Consultor
                                          </button>
                                        @endif
                                    @endis
                                  </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>

                    <div class="row">
											<div class="col-md-12 text-center">
												Total de registros: <b>{{ $clients->total() }}</b>
											</div>
										</div>
										<div class="row">
											<div class="col-md-12 text-center">
													{!! $clients->appends(\Request::except('page'))->render() !!}
											</div>
										</div>

                </div>
            </div>
        </div>
    </div>
@endsection

<script>
  function selecionaConsultor(client_id, responsavel_id)
  {
    if(responsavel_id === undefined)
    {
      responsavel_id = '';
    }

    var action_url = '{!! url('clientes/selecionar-responsavel/') !!}';
    var url = action_url + '/' + client_id + '/' + responsavel_id;

      return BootstrapDialog.show({
          title: 'Seleciona Consultor',
          message: $('<div></div>').load(url),
          buttons: [{
              label: 'Salvar',
              action: function(dialogRef){
                  $('#changeClientResponsible').submit();
                  // window.location.href = '{!! url()->full() !!}';
                  return false;
                  dialogRef.close();
              }
          }, {
              label: 'Fechar',
              action: function(dialogRef){
                  dialogRef.close();
              }
          }]
      });
  }
</script>

@section('scripts')

@endsection

resources/views/crm/cliente/info-general.blade.php
<div class="card">
  <div class="row">
    <div class="col-md-8">
      <div class="header">
        <h4 class="title">Informações do cliente</h4>
      </div>
      <div class="content">
        <label>ID CRM:</label> {!! $clienteInfo['cliente_id'] !!} | <label>ID PLATAFORMA:</label> {{ $clienteInfo['id_plataforma'] ? $clienteInfo['id_plataforma'] : "" }} </br>
        <label>RAZÃO SOCIAL:</label> {!! $clienteInfo['empresa'] !!}</br>
        <label>NOME FANTASIA:</label> {!! $clienteInfo['nome'] !!}</br>
        <label>RESPONSAVEL:</label> {!! $clienteInfo['responsavel'] !!} | {!! $clienteInfo['escritorio_nome'] !!}</br>
        <label>STATUS:</label> <span class="label label-default">{!! $clienteInfo['status'] !!}</span></br>
        <label>ORIGEM:</label> <span class="label label-default">{!! $clienteInfo['origem'] !!}</span></br>
        <label>CADASTRO PLATAFORMA:</label> <span class="label label-default">{!! $clienteInfo['datacadastro_plataforma'] !!}</span>
      </div>
    </div>
    <div class="col-md-4">
      <div class="row">
        <div class="col-md-12">
          <div class="header">
            <h4 class="title">Último login do cliente</h4>
          </div>
          <div class="content">
            {!! checkLoginTime($clienteInfo['login']['ultimo_login']) !!}
          </div>
        </div>
      </div>
      @shield('client.destroy')
      <div class="row">
        <div class="col-md-12">
          <div class="header">
            <h4 class="title">Excluir!?! Tem certeza?</h4>
          </div>
          <div class="content">
            <form role="form" id="formdeletecliente{{$clienteInfo['cliente_id']}}" class="disableonclick form-delete" method="POST" action="{{ url ('cliente/'.$clienteInfo['cliente_id']) }}" accept-charset="UTF-8">
              <input type="hidden" name="_method" value="DELETE">
              <input type="hidden" name="_token" value="{{ csrf_token() }}">
              <input type="hidden" name="cliente_id" value="{{$clienteInfo['cliente_id']}}">
              <button type="submit" class="btn btn-fill btn-xs btn-danger disableonclick sure" data-type="cliente"  data-form="#formdeletecliente{{$clienteInfo['cliente_id']}}" data-titledelete="{!! trans('cliente.titledelete') !!}" data-textdelete="{!! trans('cliente.textdelete') !!}" data-titlesuccess="{!! trans('cliente.titledelete_success') !!}" >
                  <i class="fa fa-trash-o"></i> Excluir Cliente
              </button>
            </form>
          </div>
        </div>
      </div>
      @endshield
    </div>
  </div>
</div>

resources/views/crm/cliente/interacoes.blade.php
@extends('layouts.base')
@section('content')
    <div class="row">
        <div class="col-md-12 col-xs-12 col-sm-12">

            <div class="card">
                <div class="content content-full-width">
                    @include('crm.cliente.tabs')
                    <div class="content">
                        <!-- Tab panes -->
                        <div class="tab-content">
                          <div class="tab-panel active" role="tabpanel" >

                            <div class="row">
                              <div class="col-md-12 col-xs-12 col-sm-12">
                                @include('crm.cliente.info-general')
                              </div>
                            </div>

                              @if(!$interactions->isEmpty())
                              <div class="table-responsive">
                                  <table class="table table-striped">
                                      <thead>
                                      <th>#</th>
                                      <th>Data</th>
                                      <th>Consultor</th>
                                      <th>Anterior</th>
                                      <th>Tipo</th>
                                      <th>Título</th>
                                      <th></th>
                                      </thead>
                                      <tbody>
                                      @foreach($interactions as $interaction)
                                          <tr>
                                              <td><small>{{ $interaction->id }}</small></td>
                                              <td>{{ $interaction->datacriacao }}</td>
                                              <td>{{ $interaction->author->name }}</td>
                                              <td>
                                                @if($interaction->father_id)
                                                    <a href="#" onClick="return abreModal('{{ action('Crm\ClientController@getViewInteracao', [$clienteInfo['cliente_id'], $interaction->father_id]) }}', 'Visualizando interação')" class="text-info">
                                                        <i class="fa fa-eye"></i> #{!! $interaction->father_id !!}
                                                    </a>
                                                @else
                                                    <small class="text-warning">Nenhuma</small>
                                                @endif
                                              </td>
                                              <td>
                                                <span class="label {!! $interaction->tipo_interacao_class !!}"> {!! $interaction->tipo_interacao !!}</span>
                                                @if(!is_null($interaction->children))
                                                    <a href="#" class="label label-success" onClick="return abreModal('{{ action('Crm\ClientController@getViewInteracao', [$clienteInfo['cliente_id'], $interaction->children->id]) }}', 'Visualizando interação')">
                                                        <i class="fa fa-check-circle"></i> Ver resposta
                                                    </a>
                                                @endif
                                              </td>
                                              <td>{{ substr($interaction->titulo, 0, 150) }}...</td>
                                              <td>
                                                <a href="#" onClick="return abreModal('{{ action('Crm\ClientController@getViewInteracao', [$clienteInfo['cliente_id'], $interaction->id]) }}', 'Visualizando interação')" class="btn btn-fill btn-primary btn-xs">
                                                    <i class="fa fa-eye"></i> Detalhes
                                                </a>

                                                @shield('interaction.move')
                                                <a href="#" onClick="return abreModal('{!! action('Crm\ClientController@getMoveInteraction', [$clienteInfo['cliente_id'], $interaction->id]) !!}', 'Mover interação');" class="btn btn-fill btn-xs btn-warning">
                                                    <i class="fa fa-arrows-alt"></i> Mover
                                                </a>
                                                @endshield
                                              </td>
                                          </tr>
                                      @endforeach
                                      </tbody>
                                  </table>
                                    

                                  </div>
                                  <div class="row">
                                    <div class="col-md-12 text-center">
																			{!! $interactions->appends(\Request::except('page'))->render() !!}
																	  </div>
                                  </div>
                                  <div class="clearfix margin-top"></div>
                                  @else
                                  <div class="row">
                                    <div class="col-md-12">
                                      <div class="alert alert-warning">
                                        <i class="fa fa-info"></i>Nenhum historico referente ao cliente cadastrado.
                                      </div>
                                    </div>
                                  </div>
                                  <div class="clearfix margin-top"></div>
                                  @endif
                          </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $.fn.modal.Constructor.prototype.enforceFocus = function() {};
    </script>
    <script src="{{ asset('lib/js/client.form.js') }}"></script>
    <script>
        var showProductForm = function()
        {

            $("#productInput").show();
        }
    </script>
@endsection